### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by foolhardy21**
This PR has: 
- Home Page with categories.
- Use this link for preview https://deploy-preview-1--eager-wilson-9b76d7.netlify.app/home.html

Feel free to review. Thanks.

### CODE REVIEW

**Review by nayyyhaa — APPROVED** [review]
Cood looks clean. You can merge the changes.

**Review by MayankKumar10 — APPROVED** [review]
looks good you can merge

**Review by animeshgarai09 — COMMENTED** [review]
Compress the images for better loading speed

**Comment by foolhardy21** [comment]
> Compress the images for better loading speed

thanks @animeshgarai09 . i am still working on getting the asset images. I'll definitely have different sizes of them.

**Pull request merged**
